<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_signatory_last_name</name>
   <tag></tag>
   <elementGuidId>af4608c6-6a03-4adc-87f9-ba21dbb90ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatory_last_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signatory_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e57dfd2-54c7-45fa-a25f-8a6147f6a1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>854c912d-e219-49fe-aa5b-7eae6cd04b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>30a3b338-bd6d-4e18-b024-1d0731b22a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>f9da942c-e97d-4035-a91c-e397c47bb684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>28648d6d-f7f3-4a9a-b73e-e99b09ffc231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>16731942-88c8-4faa-ad6a-5699a824e00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75a75518-3147-496c-ab5d-20012b10c479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>caac3d48-8538-4ebf-9c76-b3425e511ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatory_last_name&quot;)</value>
      <webElementGuid>dcbf7072-0a07-4e1d-a0d4-49e0b6764f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatory_last_name']</value>
      <webElementGuid>e95b0d84-48cd-43b0-9155-d0a8cef6368f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[3]/div[2]/input</value>
      <webElementGuid>d889d1df-b02c-4aff-b5a1-29e803f1e4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>208bea3c-526d-4098-ad4a-8a25fa1108b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'signatory_last_name' and @id = 'signatory_last_name' and @placeholder = 'Last name']</value>
      <webElementGuid>4decd6df-028e-44dc-9f7b-8a732b098906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
