<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_signatory_id_number</name>
   <tag></tag>
   <elementGuidId>118db63c-bf78-47a6-a26c-f2b44c9e0752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryIdNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryIdNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef77f285-d236-40e4-8a03-82091c5fc3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>a2031b07-1d1f-435c-8873-e8b58e21edac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81460ada-7433-4319-a937-cb68806cbacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>3d23490a-f187-47e4-bb15-4e46395eb23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryIdNumber</value>
      <webElementGuid>295123ba-d563-4f3e-9d80-ec4228e32018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_id_number</value>
      <webElementGuid>8161d62b-5992-4061-a5ae-3c1823d947df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryIdNumber&quot;)</value>
      <webElementGuid>aa22f6d8-9408-47a9-b547-00d6ee8f31e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryIdNumber']</value>
      <webElementGuid>1c13d674-c57a-474e-864f-9cf905d5dc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[4]/div/input</value>
      <webElementGuid>6e188a08-b292-4930-b035-fe7bf0c51736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>80120cfa-7673-4acb-8f3d-c9d7b738e9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryIdNumber' and @name = 'signatory_id_number']</value>
      <webElementGuid>a9966481-479a-462b-8533-2379e0b3f90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
