<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_signatory_email</name>
   <tag></tag>
   <elementGuidId>0d5ec164-99b3-450f-915c-de14b495a3e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46b198a6-40c8-4404-862b-17c722dc4dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>668e0897-3496-40e4-af6c-6304e3625847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>deb2ac4c-ace8-48d5-9d0b-2961f18d3a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>98d2bf38-de48-42a5-a8b9-0e75522cc827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryEmail</value>
      <webElementGuid>113bd91a-564c-4902-bf2d-33aa9855f7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_email</value>
      <webElementGuid>21770718-c222-4323-8eec-89f1f10ca3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryEmail&quot;)</value>
      <webElementGuid>425302e4-57f0-4132-a923-2b8dcc0cdcde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryEmail']</value>
      <webElementGuid>59968e9c-0eb7-4dfb-8962-6166cd653e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[3]/div/input</value>
      <webElementGuid>9b02e645-ee6b-4dc8-8ee0-9c197c43ff8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>bb4d2e34-5621-4612-96e2-fe2021b55c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryEmail' and @name = 'signatory_email']</value>
      <webElementGuid>7b13a900-a977-4bc7-8fa3-a5e84f57b79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
