<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same as company address_address_same__59d90d</name>
   <tag></tag>
   <elementGuidId>1a3db5cd-9b34-4c1d-899d-bfd712e6e586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sameCompanyAddressCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sameCompanyAddressCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1767e56e-4bfa-41e5-b0e6-2bb686dbb26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>86423ab7-2b42-41ed-a55d-bdd26adcb38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>967b8420-750b-4859-81d5-876e2e0d09f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_same_as_company</value>
      <webElementGuid>c91fb083-3f60-4d74-acb4-34fef3b85c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sameCompanyAddressCheck</value>
      <webElementGuid>d4557edb-b220-4bbb-9877-b7dcd67a6762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sameCompanyAddressCheck&quot;)</value>
      <webElementGuid>15474d53-99b2-4fc3-98eb-c53edf9b4356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sameCompanyAddressCheck']</value>
      <webElementGuid>3f7d8229-2fef-46ce-ad0f-9a257cb6b2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[6]/div/div/label/input</value>
      <webElementGuid>d5371db8-3048-45eb-a6e5-17693d920ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/label/input</value>
      <webElementGuid>99a9b64f-caea-4c1c-9163-13e22b78f7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'address_same_as_company' and @id = 'sameCompanyAddressCheck']</value>
      <webElementGuid>cea27ea9-c047-43f9-aa6a-650b3d49d2a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
