<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_form-control minor-edit _a4e6be</name>
   <tag></tag>
   <elementGuidId>515ac689-6390-4fa0-8c23-e40e1c3f083d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#step-2 > div.panel-body.col-sm-12 > div.form-group.pay-form > div.col-sm-8 > div.iti.iti--allow-dropdown.iti--separate-dial-code > input.form-control.minor-edit.int_tel_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b19b3555-c972-46fa-b8b6-26a1dfb755ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>d8101bc8-c71a-49ea-971e-d8b5305ef3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d7553a5-d4a0-4142-804e-32865574df4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit int_tel_input</value>
      <webElementGuid>f3d225d1-e1ef-4333-9596-d712e4664d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7035fed2-8ad5-4b92-918c-3d5c0f456772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>dbc626f4-e8d3-4a4b-af17-55cfdc44c075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-1</value>
      <webElementGuid>eff940da-9038-4904-b919-998943328f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>18fb889e-5fdd-4729-b823-9a2dae335d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>58c62e46-06ef-48d6-8bcf-96e02664e42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-2&quot;)/div[@class=&quot;panel-body col-sm-12&quot;]/div[@class=&quot;form-group pay-form&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control minor-edit int_tel_input&quot;]</value>
      <webElementGuid>7658a7cf-45d6-4825-8065-5952c34f2e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[16]</value>
      <webElementGuid>a79ea353-b98d-42b7-8704-64da169e2413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[5]/div/div/input</value>
      <webElementGuid>3314e5d3-f403-4d2a-9a0d-b0c155fec640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/input</value>
      <webElementGuid>20a70513-09e7-4353-a37f-d48fbcd598ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '812-345-678']</value>
      <webElementGuid>7cfd2ed2-8e6b-4f4d-a62e-7fbc4c3b2cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
