<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Savings                    Cheque   _bc224e</name>
   <tag></tag>
   <elementGuidId>099fb84e-4ba3-4136-8a40-ed61ab59382a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input_account_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_account_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dcbca0cb-b1f7-46ec-8133-a132b44cd7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>acf483b0-71a9-4e38-87e7-29223be7b2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>4bc49e68-57ce-412b-b1c5-2818fe09e477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_type</value>
      <webElementGuid>b11a2b47-a9c8-4a6c-bc54-14f227b6ccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_account_type</value>
      <webElementGuid>3d06ec62-2800-4d54-9645-967eb5259108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Savings
                    Cheque
                    Business
                    Checking
                    Other
                </value>
      <webElementGuid>34cc3bc9-8948-469e-b3e4-6801af416403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_account_type&quot;)</value>
      <webElementGuid>c21df4d4-3189-4dec-8b05-0e31052509cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input_account_type']</value>
      <webElementGuid>fee4ec5e-c063-410e-a8ed-92db6df1e638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div[3]/div/select</value>
      <webElementGuid>83dd25ae-ba43-4558-b2d2-53472e41c5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Type'])[1]/following::select[1]</value>
      <webElementGuid>dabe5d3a-5a3e-466c-97a3-b5912a0154b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number'])[1]/following::select[1]</value>
      <webElementGuid>86fe1e88-e553-4bb1-b523-48e23b7d6dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/preceding::select[1]</value>
      <webElementGuid>2277fa74-77cd-4aa3-95c5-4c640ff74d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Country'])[1]/preceding::select[1]</value>
      <webElementGuid>e6a06e9f-f617-4d0b-a4f5-ae5e23ad2a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>b141c9fd-41e6-454b-b877-c48b19663eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_type' and @id = 'input_account_type' and (text() = '
                    Savings
                    Cheque
                    Business
                    Checking
                    Other
                ' or . = '
                    Savings
                    Cheque
                    Business
                    Checking
                    Other
                ')]</value>
      <webElementGuid>48872b30-ffb7-407c-8292-bb9c8ed668d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
